### ISSUE TITLE
[cubing.js issue] Broken SVG state editor 

### ISSUE THREAD

**Issue by lgarron** [cubing/cubing.js#297]
### Steps to reproduce the issue

1. Visit https://experiments.cubing.net/cubing.js/svg-state-editor/

### Observed behaviour

```
index.ts:276 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'addEventListener')
    at new h (index.ts:276:18)
    at a.display (index.ts:181:27)
    at a.setPuzzleSync (index.ts:158:10)
    at a.createAsync (index.ts:130:14)
    at async m.displayStateText (index.ts:104:43)
```

### Expected behaviour

No error.

### Environment

Chrome 117.0.5938.132

**Comment by lgarron** [comment]
Aha, I was using an outdated URL from my browser history: https://experiments.cubing.net/cubing.js/svg-pattern-editor/?puzzle=3x3x3

I'll delete old files on the server.
